-- Initialize schema

CREATE DATABASE IF NOT EXISTS chill;

CREATE TABLE IF NOT EXISTS chill.command_log (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT 'primary key',
    build_no VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'build no',
    command TEXT COMMENT 'command',
    remark VARCHAR(1000) NOT NULL DEFAULT '' COMMENT 'remark',
    status VARCHAR(10) NOT NULL DEFAULT '' COMMENT 'status: SUCCESSFUL, FAILED',
    ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'created at',
    KEY build_no_idx (build_no)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='Command Log';

CREATE TABLE IF NOT EXISTS chill.build_info (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT 'primary key',
    name VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'build name',
    status VARCHAR(10) NOT NULL DEFAULT '' COMMENT 'status: SUCCESSFUL, FAILED',
    ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'created at',
    utime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated at',
    UNIQUE KEY name_uk (name)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='Build Info';

CREATE TABLE IF NOT EXISTS chill.build_log (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT 'primary key',
    build_no VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'build no',
    name VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'build name',
    status VARCHAR(10) NOT NULL DEFAULT '' COMMENT 'status: SUCCESSFUL, FAILED',
    remark VARCHAR(1000) NOT NULL DEFAULT '' COMMENT 'remark',
    ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'created at',
    utime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated at',
    KEY name_idx (name),
    UNIQUE KEY build_no_uk (build_no)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='Build Log';